version: "3"
services:
  rails:
    build: .
    volumes:
      - ./:/usr/src/app
    environment:
      TZ: "Asia/Tokyo"
      RAILS_ENV: 'development'
      RACK_ENV: 'development'
    ports:
      - "3000:3000"
